### ISSUE TITLE
支付以外接口设计

### ISSUE THREAD

**Issue by Akagilnc** [monstarlab-chengdu-product-factory/automatic-test-server#5]
- [ ] 退款接口
- [ ] 退款查询
- [ ] 退款状态查询
- [ ] 流水查询
- [ ] API说明接口

**Comment by ghost** [comment]
@DeronLee  业务：支付结果通知（统一通知格式）回调方式  划分到他们支付回调一起处理吧

**Comment by ghost** [comment]
微信退款：退款有一定延时，用零钱支付的退款20分钟内到账，银行卡支付的退款3个工作日后重新查询退款状态。

**Comment by Akagilnc** [comment]
@xiandingwang 
ok. 我会把这个写到wiki里面去
另外我会把这个issue转移到支付系统的repo里面

**Comment by ghost** [comment]
退款申请接口：<br/><div class="ennote"><div>入参：</div><table style="-evernote-table:true;border-collapse:collapse;width:100%;table-layout:fixed;margin-left:0px;"><tbody><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>字段</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>类型</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>说明</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">是否必传(默认true)</span></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>out_trade_no</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">商户订单号</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">out_refund_no</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>商户退款单号</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">total_fee</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">bigdecimal</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>订单总金额</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>refund_fee</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">bigdecimal</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>退款金额</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">refund_desc</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">退款原因</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>false</div></td></tr></tbody></table><div><br></div><div>返回参数:</div><table style="-evernote-table:true;border-collapse:collapse;width:100%;table-layout:fixed;margin-left:0px;"><tbody><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>字段</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>类型</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>说明</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">是否必传(默认true)</span></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">out_trade_no</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>商户订单号</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">out_refund_no</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>商户退款单号</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">refund_id</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style="font-family:gotham, helvetica, arial, sans-serif;font-size:14px;">String</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">支付平台退款单号</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">refund_fee</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>bigdecimal</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>退款金额</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr><tr><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><span style=" color: rgb(34, 34, 34) ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ">total_fee</span></div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>bigdecimal</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div>订单总金额</div></td><td style="border-style:solid;border-width:1px;border-color:rgb(211,211,211);padding:10px;margin:0px;width:25%;"><div><br></div></td></tr></tbody></table><div><br></div><div><br></div></div>
